name: ðŸ§± Build + ðŸ§ª Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16.x]

    name: ${{ matrix.os }} (Node.js ${{ matrix.node-version }})

    steps:
      - name: ðŸš¨ Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }} âš™
        if: matrix.os == 'windows-latest'
        run: |
          curl -sL https://nodejs.org/dist/latest/node-v${{ matrix.node-version }}-x64.msi -o node.msi
          start /wait node.msi
          echo "Node.js installed"
      - name: Setup Node.js ${{ matrix.node-version }} âš™ - Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: âš™ï¸ Setup PNPM - Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm install -g pnpm
          echo "PNPM installed"
      - name: âš™ï¸ Setup PNPM - Linux
        if: matrix.os == 'ubuntu-latest'
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: ðŸ–¥ï¸ Run display server
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - name: ðŸ“¦ Install node_modules
        run: pnpm install --frozen-lockfile
        env:
          CI: true
          DEBUG: "*"
      - name: ðŸ’¾ Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ðŸš€ Test + Build
        run: |
          pnpm test
          pnpm run vscode:prepublish
        env:
          DISPLAY: ':99.0'
          CI: true
          DEBUG: "*"
