name: ðŸ§± Build + ðŸ§ª Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16.x]

    name: ${{ matrix.os }} (Node.js ${{ matrix.node-version }})

    steps:
      - name: ðŸš¨ Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }} âš™
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: âš™ï¸ Setup PNPM and install @nyxb/nyxi
        run: |
          pnpm install -g @nyxb/nyxi
          nyxi --version

      - name: ðŸ–¥ï¸ Run display server
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}

      - name: ðŸ“¦ Install node_modules
        run: pnpm install --frozen-lockfile

      - name: ðŸ’¾ Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ðŸš€ Test + Build
        run: |
          pnpm test
          pnpm run vscode:prepublish
        env:
          DISPLAY: ':99.0'
